package com.example.scanpro.data.local.db

import androidx.room.Database
import androidx.room.RoomDatabase

/**
 * The Room database for the ScanPro application.
 *
 * This abstract class is the main access point to the app's persisted relational data.
 * Room generates the concrete implementation at compile time based on the declared
 * [entities] and abstract DAO accessor methods.
 *
 * ### Versioning
 * - **Version 1** — Initial schema containing the [BarcodeEntity] table.
 * - [exportSchema] is set to `false` because schema history is tracked via version
 *   control rather than Room's JSON schema files. If automated migration testing is
 *   introduced later, this should be flipped to `true` and the `room.schemaLocation`
 *   annotation-processor argument should be configured in `build.gradle`.
 *
 * ### Dependency injection
 * The database instance is **not** created here. Instead, a Hilt `@Module` provides
 * a singleton [AppDatabase] built via `Room.databaseBuilder(...)`, ensuring a single
 * connection pool is shared across the entire app process.
 *
 * ### Migration strategy
 * For future schema changes, create a [androidx.room.migration.Migration] object
 * (or use `autoMigrations` on API 28+) and register it with the builder.
 * **Do not** use `fallbackToDestructiveMigration()` in production — users' scan
 * history would be lost.
 *
 * @see BarcodeEntity  The sole entity in version 1 of this database.
 * @see BarcodeDao     The DAO exposing all CRUD operations on the `barcodes` table.
 */
@Database(
    entities = [BarcodeEntity::class],
    version = 1,
    exportSchema = false
)
abstract class AppDatabase : RoomDatabase() {

    /**
     * Returns the [BarcodeDao] implementation generated by Room.
     *
     * Callers should obtain this DAO through the Hilt-provided [AppDatabase]
     * singleton rather than constructing it manually.
     *
     * @return A concrete [BarcodeDao] backed by this database's `barcodes` table.
     */
    abstract fun barcodeDao(): BarcodeDao
}
